[build]
  # No build step. We serve static files from /public.
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" # default on Netlify; fine even with no deps

# ---------- API routes → Netlify Functions ----------
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# (Optional explicit mapping; redundant with the wildcard above but harmless)
[[redirects]]
  from = "/api/make_card"
  to   = "/.netlify/functions/make_card"
  status = 200

# ---------- API headers (no cache + CORS) ----------
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# ---------- SPA fallback (static files take precedence) ----------
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# ---------- Scheduled functions ----------
# Nightly cleanup of old draft deploys published via /api/publish_via_deploy
[[scheduled]]
  path = "/.netlify/functions/cleanup_deploys"
  schedule = "@daily"
